dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('trainbot/', views.trainbot, name='trainbot'),
    path('perfil/', views.perfil, name='perfil'),
    path('changePassword',views.change_password, name='change_password'),
    path('reportes/', views.reportes, name='reportes'),
    path('reporteAtendido/<slug:identificador>', views.resolverReporte, name='reporteAtendido'),
    path('reporte/<slug:identificador>', views.reporte, name='reporte'),
    path('conversaciones/', views.conversaciones, name='conversaciones'),
    path('conversacion/<slug:identificador>', views.conversacion, name='conversacion'),
    path('user/<slug:identificador>', views.del_user, name='deleteUser'),
    path('searchReport/', views.searchReport, name='searchReport'),
    path('searchConversacion/', views.searchConversacion, name='searchConversacion'),
    path('users/', views.users, name='users'),
]

proyecto_is/urls.py
from django.urls import path
from users_auth.urls import urlpatterns as account_urls
from dashboard.urls import urlpatterns as dashboard_urls
from django.conf.urls import include
from . import views
from django.conf.urls import url
from dashboard.views import ReportCreate

urlpatterns = [
    path('', views.index, name='index'),
    path('chatbot/', views.chatear, name='chatear'),
    path('createCita', ReportCreate.as_view(), name='createCita'),
    path('account/',include((account_urls, 'account'), namespace='account')),    
    path('dashboard/',include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^api/chatterbot/', views.ChatterBotApiView.as_view(), name='chatterbot'),
    url(r'^api/chatterbotAdmin/', views.ChatterBotApiViewAdmin.as_view(), name='chatterbotadmin'),
]

dashboard/models.py
from django.db import models
from django.utils.timezone import now 

class Conversacion(models.Model):
    create = models.DateTimeField(default=now , editable=False)
    solucionado = models.BooleanField(default=False)
    texto = models.CharField(max_length=512)
    enviadopor = models.CharField(max_length=36)
    response = models.CharField(max_length=36, default='BOT')


class Reporte(models.Model):
    create = models.DateTimeField(default=now, editable=False)
    problema = models.CharField(max_length=1000)
    atendido = models.BooleanField(default=False)
    modelopc = models.CharField(max_length=100)
    cliente = models.CharField(max_length=150)
    fecha = models.DateField(default=now)
    hora = models.TimeField(default=now)
    def __str__(self):
        return self.modelopc

proyecto_is/forms.py
from django import forms

proyecto_is/views.py
from django.shortcuts import render,redirect 
import datetime
from django.contrib.auth.decorators import login_required
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from django.views.generic.base import TemplateView
from django.views.generic import View
import json
from chatterbot.conversation import Statement
from django.http import JsonResponse
from chatterbot.trainers import ChatterBotCorpusTrainer
import random
from dashboard.models import Conversacion, Reporte
import string
from chatterbot.comparisons import LevenshteinDistance
from chatterbot.parsing import datetime_parsing
from chatterbot.response_selection import get_most_frequent_response
from datetime import datetime
from chatterbot.trainers import ListTrainer
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from users_auth.forms import ReporteForm

levenshtein_distance = LevenshteinDistance()

class ChatterBotApiView(View):
    bot = ChatBot(**settings.CHATTERBOT)
    def post(self, request, *args, **kwargs):
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text'] == '' or input_data['id'] == '':
            return JsonResponse({
                'text': [
                    'El atributo texto o id son requeridos'
                ]
            }, status=400)
        else:
            conversa = Conversacion(texto=input_data['text'],enviadopor=input_data['id'], response='USER')
            conversa.save()
            respuesta = Statement(input_data['text'])
            if levenshtein_distance.compare(respuesta, Statement('Si funciono'))>0.65 or levenshtein_distance.compare(respuesta, Statement('Se soluciono el problema'))>0.65:
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                response = self.bot.get_response(input_data)
                print(response)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'], solucionado=True)
                conversa.save()
            elif levenshtein_distance.compare(respuesta, Statement('Necesito una cita de reparacion'))>0.65:
                response = Statement('Cita de reparacion')
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                conversa = Conversacion(texto='Por favor llena el siguiente formulario para agendar tu cita',enviadopor=input_data['id'])
                conversa.save()
            else:
                response = self.bot.get_response(input_data)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'])
                conversa.save()
                print(type(response))
            response_data = response.serialize()
            return JsonResponse(response_data, status=200)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

class ChatterBotApiViewAdmin(View):
    def post(self, request, *args, **kwargs):
        bot = ChatBot(**settings.CHATTERBOT)
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text1'] == '' or input_data['text2'] == '':
            return JsonResponse({
                'text': [
                    'Los campos texto son requeridos'
                ]
            }, status=400)
        else:
            respuesta = Statement(input_data['text1'])
            correccion = Statement(input_data['text2'])
            trainer = ListTrainer(bot)
            trainer.train([
                input_data['text1'],
                input_data['text2']
            ])
            response = "Nueva respuesta aprendida a la pregunta " +input_data['text1'] + " respondere " + input_data['text2']
            response_data = json.dumps(response)
            return JsonResponse(response_data, status=200, safe=False)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

def index(request):
    return render(request, 'chatbot/index.html')

def chatear(request):
    letters = string.ascii_lowercase
    identificador = ''.join(random.choice(letters) for i in range(12))
    form = ReporteForm
    return render(request, 'chatbot/chatbot.html', {'idC':identificador, 'form':form})

proyecto_is/templates/chatbot/chatbot.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<style>
    .card-title {
        padding: 10px;
    }

    .card-title {
        min-height: 57px;
    }

    .message-content {
        border: 1px solid #dcdada;
        background: #f9f9f9;
    }

    .message {
        background: #f1f0f0;
        border-radius: 4px;
        padding: 10px;
        margin-bottom: 10px;
    }

    .message-support {
        background: #448AFF;
        color: #fff;
        margin-left: 580px;
    }

    p.message-title {
        font-size: 18px;
    }

    h5 {
        display: inline-block;
    }

    .message-left {
        margin-right: 580px;
    }

    ::-webkit-scrollbar {
        width: 15px;
    }

    ::-webkit-scrollbar-track {
        background: #ddd;
    }

    ::-webkit-scrollbar-thumb {
        background: #002a38;
    }

    ::-webkit-scrollbar-thumb:hover {
        background: #555;
    }
</style>
<br>
<h1 class="center" data-aos="fade-up">Soporte Técnico</h1>
<h5 class="center">Escribe un mensaje para comenzar</h5>
<div class="container">
    <div class="container">
        <div class="container">
            <div class="card message-card">
                <div class="card-title">
                    <h5>CHATBOT</h5>
                </div>
                <div class="card-content message-content" id="content_messages"
                    style="max-height: 300px; overflow-y: scroll;">
                </div>
                <div class="card-footer bottom" id="bottom">
                    <div class="row" style="margin: 0px;">
                        <div class="input-field col s11" style="margin: 0px;">
                            <input type="text" id="mensaje" class="materialize-textarea js-text"
                                placeholder="Escribe tu mensaje">
                        </div>
                        <div class="input-field col s1" style="margin: 0px;">
                            <button type="submit" class="btn btn-floating waves-effect waves-light js-say"
                                style="padding: 0px!important;">
                                <i class="material-icons">send</i>
                            </button>
                        </div>
                        <button onclick="dictarPregunta()" class="btn btn-primary narrow center dictarMsn">Dictar
                            Mensaje</button>
                    </div>
                </div>
                <p>*Para obtener respuestas óptimas trata de ser lo más explícito al realizar tus preguntas.</p>
            </div>
            <div class="createCita">

            </div>
        </div>
    </div>
</div>
{% csrf_token %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/js.cookie.js' %}"></script>
<script>
    var chatterbotUrl = '{% url "chatterbot" %}';
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    var $chatlog = $('.card-content');
    var $input = $('.js-text');
    var $sayButton = $('.js-say');
    var $dictarButton = $('.dictarMsn');
    var $citaSoporte = $('.createCita');
    var texto = ""

    function createRowBot(text) {
        texto = text.replace(/(?:\\r\\n|\\r|\\n)/g, '<br />');
        var $row = '<div class="message message-left"><p class="message-title"><span>ORWELL</span><p class="message-text">' + texto + '</p></p></div>';
        $chatlog.append($row);
    }

    function createRowUser(text) {
        var $row = '<div class="message message-support"><p class="message-title"><span>Usuario</span><p class="message-text">' + text + '</p></p></div>';
        $chatlog.append($row);
    }

    function submitInput() {
        var inputData = {
            'text': $input.val(),
            'id': "{{ idC }}"
        }
        createRowUser(inputData.text);
        var $submit = $.ajax({
            type: 'POST',
            url: chatterbotUrl,
            data: JSON.stringify(inputData),
            contentType: 'application/json'
        });
        $submit.done(function (statement) {
            if (statement.text == "Cita de reparacion") {
                $input.prop("disabled", true);
                $sayButton.prop("disabled", true);
                $dictarButton.prop("disabled", true);
                var $row = '{% include "../snippet/createCita.html" %}';
                $citaSoporte.append($row)
                document.getElementById('id_fecha').valueAsDate = new Date();
                createRowBot('Por favor llena el siguiente formulario para agendar tu cita');
                const direccion = document.querySelector('#submit-report');
                const form = document.getElementById('report_form');
                form.addEventListener('click', function () {
                    form.addEventListener("submit", function (event) {
                        event.preventDefault();
                        event.stopImmediatePropagation();
                        var xhttp = new XMLHttpRequest();
                        xhttp.open('POST', '{% url "createCita" %}', true);
                        xhttp.onreadystatechange = function () {
                            if (xhttp.status === 200 && xhttp.readyState === 4) {
                                if (xhttp.responseText) {
                                    var response = JSON.parse(this.responseText);
                                    if(response=='Ok'){
                                        $citaSoporte.fadeOut(400, function(){ $(this).remove();});
                                        var cliente = $("#id_cliente").val();
                                        var modelo = $("#id_modelopc").val();
                                        var problema = $("#id_problema").val();
                                        var fecha = $("#id_fecha").val();
                                        var hora = $("#id_hora").val();
                                        createRowBot("Entendido, guarde una cita para "+cliente+" con el modelo de computadora "+modelo+" para el dia "+fecha+" a las "+hora+ " con el siguiente diagnostico "+problema);
                                    }
                                }
                            } else if (xhttp.status === 500) {
                                console.log("Error");
                                document.getElementById("msnError").innerHTML = 'La fecha seleccionada ya no esta disponible';
                            }
                        }
                        xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                        xhttp.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                        var data = new FormData(form);
                        data.append('idC', '{{ idC }}');
                        xhttp.send(data);
                    });
                });
            }
            else {
                createRowBot(statement.text);
            }
            $input.val('');
            $chatlog[0].scrollTop = $chatlog[0].scrollHeight;
        });

        $submit.fail(function () {
            console.log("Error");
        });
    }

    $sayButton.click(function () {
        submitInput();
    });

    $input.keydown(function (event) {
        if (event.keyCode == 13) {
            submitInput();
        }
    });

</script>
<script>
    function dictarPregunta() {
        window.SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition;
        let finalTranscript = '';
        let recognition = new window.SpeechRecognition();
        recognition.interimResults = true;
        recognition.maxAlternatives = 10;
        recognition.continuous = true;
        recognition.lang = 'es-MX';
        recognition.onresult = (event) => {
            let interimTranscript = '';
            for (let i = event.resultIndex, len = event.results.length; i < len; i++) {
                let transcript = event.results[i][0].transcript;
                if (event.results[i].isFinal) {
                    finalTranscript += transcript;
                } else {
                    interimTranscript += transcript;
                }
            }
            document.getElementById('mensaje').value = finalTranscript + interimTranscript;
        }
        recognition.start();
    }
</script>

{% endblock %}

proyecto_is/templates/chatbot/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="slider">
    <ul class="slides" style="position: relative!important;
    max-width:100% auto!important;
    height:auto!important;
    filter: brightness(80%) saturate(140%)!important;">
        <li>
            <img class="imageCarousel" src="{% static 'images/background3.png' %}">
            <div class="caption center-align">
                <h1 class="black-text title" style="font-weight: 600;">ORWELL </h1>
                <h3 class="black-text" style="font-weight: 600;">Bot para facilitar la reparación de tu equipo de computo</h3>
            </div>
        </li>
    </ul>
</div>
<div class="container">
    <div class="row">
        <div class="col s12 m6">
            <h4 data-aos="fade-right" data-aos-offset="400" style="margin-top: 50px;">¿Como funciona?</h4>
            <p class="text-justified" data-aos="fade-right" data-aos-offset="400">Orwell es un programa que utiliza diferentes técnicas de machine learning, de las cuales se toman los principales algoritmos de búsqueda y clasificación bayesianos, con estos se toman ciertos criterios que determinan una respuesta óptima para mantener la conversación y dar solución al problema del usuario.
            Para esto se realiza un entrenamiento en el cual mientras más.</p>
        </div>
        <div class="col s12 m6">
            <img class="responsive" style="border-radius: 50px; margin-top: 50px;" data-aos="fade-left" data-aos-offset="500" src="{% static 'images/bg1.png' %}">
        </div>
    </div>
    <div class="row">
        <div class="col s12 m6">
            <img class="responsive" data-aos="fade-right"  data-aos-offset="400" style="border-radius: 50px; " src="{% static 'images/bg11.png' %}">
        </div>
        <div class="col s12 m6">
            <h4 data-aos="fade-left">¿Para qué sirve?</h4>
            <p class="text-justified" data-aos="fade-left">Orwell es un programa diseñado para dar soluciones a tus problemas con tu equipo de cómputo, es decir, si tu equipo de cómputo tiene algún problema con su software, Orwell te brindara diferentes opciones con las cuales podrás dar solución a tu problema. Y si tu problema estuviera relacionado con el hardware Orwell también cuenta con la opción de agendar una cita con un técnico de confianza el cual te indicara lo que necesita tu equipo para su reparación.</p>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m6">
            <h4 data-aos="fade-right">Ventajas</h4>
        <div data-aos="fade-right">
            <p class="text-justified">- Facilita el soporte técnico.</p>
            <p class="text-justified">- Agiliza las reparaciones.</p>
            <p class="text-justified">- Interfaz intuitiva y fácil de usar.</p>
            <p class="text-justified">- Respuestas son rápidas, concretas y claras.</p>
        </div>
        </div>
        <div class="col s12 m6">
            <img class="responsive" style="border-radius: 50px;" data-aos="fade-left" data-aos-offset="400" src="{% static 'images/bg3.png' %}">
        </div>
    </div>
</div>
{% endblock %}