dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('trainbot/', views.trainbot, name='trainbot'),
    path('perfil/', views.perfil, name='perfil'),
    path('changePassword',views.change_password, name='change_password'),
    path('reportes/', views.reportes, name='reportes'),
    path('reporteAtendido/<slug:identificador>', views.resolverReporte, name='reporteAtendido'),
    path('reporte/<slug:identificador>', views.reporte, name='reporte'),
    path('conversaciones/', views.conversaciones, name='conversaciones'),
    path('conversacion/<slug:identificador>', views.conversacion, name='conversacion'),
    path('user/<slug:identificador>', views.del_user, name='deleteUser'),
    path('searchReport/', views.searchReport, name='searchReport'),
    path('searchConversacion/', views.searchConversacion, name='searchConversacion'),
    path('users/', views.users, name='users'),
]

proyecto_is/urls.py
from django.urls import path
from users_auth.urls import urlpatterns as account_urls
from dashboard.urls import urlpatterns as dashboard_urls
from django.conf.urls import include
from . import views
from django.conf.urls import url
from dashboard.views import ReportCreate

urlpatterns = [
    path('', views.index, name='index'),
    path('chatbot/', views.chatear, name='chatear'),
    path('createCita', ReportCreate.as_view(), name='createCita'),
    path('account/',include((account_urls, 'account'), namespace='account')),    
    path('dashboard/',include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^api/chatterbot/', views.ChatterBotApiView.as_view(), name='chatterbot'),
    url(r'^api/chatterbotAdmin/', views.ChatterBotApiViewAdmin.as_view(), name='chatterbotadmin'),
]

users_auth/urls.py
from django.contrib.auth import views as django_views
from django.urls import path
from django.urls import reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),  
    path('password-reset/',
         django_views.PasswordResetView.as_view(
             subject_template_name = 'account/password_reset_subject.txt',
             success_url = reverse_lazy('account:password_reset_done'),
             template_name='account/password_reset.html',
             email_template_name='account/password_reset_email.html',
         ),
         name='password_reset'),
    path('password-reset/done/',
         django_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', 
        django_views.PasswordResetConfirmView.as_view(
            success_url = reverse_lazy('account:password_reset_complete'),
            template_name='account/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'),
    path('password-reset/complete', 
        django_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html'
            ), 
            name='password_reset_complete'
        ),
]

proyecto_is/forms.py
from django import forms

proyecto_is/views.py
from django.shortcuts import render,redirect 
import datetime
from django.contrib.auth.decorators import login_required
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from django.views.generic.base import TemplateView
from django.views.generic import View
import json
from chatterbot.conversation import Statement
from django.http import JsonResponse
from chatterbot.trainers import ChatterBotCorpusTrainer
import random
from dashboard.models import Conversacion, Reporte
import string
from chatterbot.comparisons import LevenshteinDistance
from chatterbot.parsing import datetime_parsing
from chatterbot.response_selection import get_most_frequent_response
from datetime import datetime
from chatterbot.trainers import ListTrainer
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from users_auth.forms import ReporteForm

levenshtein_distance = LevenshteinDistance()

class ChatterBotApiView(View):
    bot = ChatBot(**settings.CHATTERBOT)
    def post(self, request, *args, **kwargs):
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text'] == '' or input_data['id'] == '':
            return JsonResponse({
                'text': [
                    'El atributo texto o id son requeridos'
                ]
            }, status=400)
        else:
            conversa = Conversacion(texto=input_data['text'],enviadopor=input_data['id'], response='USER')
            conversa.save()
            respuesta = Statement(input_data['text'])
            if levenshtein_distance.compare(respuesta, Statement('Si funciono'))>0.65 or levenshtein_distance.compare(respuesta, Statement('Se soluciono el problema'))>0.65:
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                response = self.bot.get_response(input_data)
                print(response)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'], solucionado=True)
                conversa.save()
            elif levenshtein_distance.compare(respuesta, Statement('Necesito una cita de reparacion'))>0.65:
                response = Statement('Cita de reparacion')
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                conversa = Conversacion(texto='Por favor llena el siguiente formulario para agendar tu cita',enviadopor=input_data['id'])
                conversa.save()
            else:
                response = self.bot.get_response(input_data)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'])
                conversa.save()
                print(type(response))
            response_data = response.serialize()
            return JsonResponse(response_data, status=200)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

class ChatterBotApiViewAdmin(View):
    def post(self, request, *args, **kwargs):
        bot = ChatBot(**settings.CHATTERBOT)
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text1'] == '' or input_data['text2'] == '':
            return JsonResponse({
                'text': [
                    'Los campos texto son requeridos'
                ]
            }, status=400)
        else:
            respuesta = Statement(input_data['text1'])
            correccion = Statement(input_data['text2'])
            trainer = ListTrainer(bot)
            trainer.train([
                input_data['text1'],
                input_data['text2']
            ])
            response = "Nueva respuesta aprendida a la pregunta " +input_data['text1'] + " respondere " + input_data['text2']
            response_data = json.dumps(response)
            return JsonResponse(response_data, status=200, safe=False)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

def index(request):
    return render(request, 'chatbot/index.html')

def chatear(request):
    letters = string.ascii_lowercase
    identificador = ''.join(random.choice(letters) for i in range(12))
    form = ReporteForm
    return render(request, 'chatbot/chatbot.html', {'idC':identificador, 'form':form})

proyecto_is/templates/base/base.html
{% load static %}
<html>
<head>
    <title>ORWELL</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    {% block extra_head %}{% endblock %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>
<body>
    {% if user.is_authenticated %}
        {% if user.is_admin %}
            <header>
                <div class="navbar-fixed ">
                    <nav>
                        <div class="nav-wrapper">
                            <a href="{% url 'dashboard:profile' %}" class="brand-logo"><img class="logo hide-on-med-and-down"
                                    src="{% static 'images/logo.png' %}"><span class="logo hide-on-med-and-up">ORWELL</span>
                            </a>
                            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i
                                    class="material-icons navbarIcon">menu</i></a>
                            <ul class="right hide-on-med-and-down elementsRight">
                                <li><a class="menuItem" href="{% url 'dashboard:trainbot' %}">ENTRENAR AL BOT</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:perfil' %}">PERFIL</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:users' %}">USUARIOS</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:reportes' %}">REPARACIONES</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:conversaciones' %}">CONVERSACIONES</a></li>
                                <li><a class="menuItem" href="{% url 'account:logout' %}">CERRAR SESION</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <ul class="sidenav" id="mobile-demo">
                    <li><a class="menuItem" href="{% url 'index' %}">Inicio</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:trainbot' %}">ENTRENAR AL BOT</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:perfil' %}">PERFIL</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:users' %}">USUARIOS</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:reportes' %}">REPARACIONES</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:conversaciones' %}">CONVERSACIONES</a></li>
                    <li><a class="menuItem" href="{% url 'account:logout' %}">CERRAR SESION</a></li>
                </ul>
            </header>
        {% elif user.is_staff %}
            <header>
                <div class="navbar-fixed ">
                    <nav>
                        <div class="nav-wrapper">
                            <a href="{% url 'dashboard:profile' %}" class="brand-logo"><img class="logo hide-on-med-and-down"
                                    src="{% static 'images/logo.png' %}"><span class="logo hide-on-med-and-up">ORWELL</span>
                            </a>
                            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i
                                    class="material-icons navbarIcon">menu</i></a>
                            <ul class="right hide-on-med-and-down elementsRight">
                                <li><a class="menuItem" href="{% url 'dashboard:perfil' %}">PERFIL</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:reportes' %}">REPARACIONES</a></li>
                                <li><a class="menuItem" href="{% url 'dashboard:conversaciones' %}">CONVERSACIONES</a></li>
                                <li><a class="menuItem" href="{% url 'account:logout' %}">CERRAR SESION</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <ul class="sidenav" id="mobile-demo">
                    <li><a class="menuItem" href="{% url 'index' %}">Inicio</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:perfil' %}">PERFIL</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:reportes' %}">REPARACIONES</a></li>
                    <li><a class="menuItem" href="{% url 'dashboard:conversaciones' %}">CONVERSACIONES</a></li>
                    <li><a class="menuItem" href="{% url 'account:logout' %}">CERRAR SESION</a></li>
                </ul>
            </header>
        {% endif %}
        {% else %}
        <header>
            <div class="navbar-fixed ">
                <nav>
                    <div class="nav-wrapper">
                        <a href="{% url 'index' %}" class="brand-logo"><img class="logo hide-on-med-and-down"
                                src="{% static 'images/logo.png' %}"><span class="logo hide-on-med-and-up">ORWELL</span>
                        </a>
                        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i
                                class="material-icons navbarIcon">menu</i></a>
                        <ul class="right hide-on-med-and-down elementsRight">
                            <li><a class="menuItem" href="{% url 'account:login' %}">INICIAR SESION</a></li>
                            <li><a class="menuItem" href="{% url 'account:signup' %}">REGISTRO</a></li>
                            <li><a class="menuItem" href="{% url 'chatear' %}">CHAT CON ORWELL</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
            <ul class="sidenav" id="mobile-demo">
                <li><a class="menuItem" href="{% url 'index' %}">INDEX</a></li>
                <li><a class="menuItem" href="{% url 'account:login' %}">INICIAR SESION</a></li>
                <li><a class="menuItem" href="{% url 'account:signup' %}">REGISTRO</a></li>
                <li><a class="menuItem" href="{% url 'chatear' %}">CHAT CON ORWELL</a></li>
            </ul>
        </header>
    {% endif %}
    {% block content %}
    {% endblock %}
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.slider');
            var instances = M.Slider.init(elems, { indicators: false, height: 500 });
        });

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems);

        });

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.carousel');
            var options = { fullWidth: true, indicators: true }
            var instances = M.Carousel.init(elems, options);
        });

        var collapsibles = document.querySelectorAll('.collapsible')
        for (var i = 0; i < collapsibles.length; i++) {
            M.Collapsible.init(collapsibles[i]);
        }

        var elems = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(elems, { format: 'mm/dd/yyyy', yearRange: 100 });
    </script>
</body>
</html>