dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('trainbot/', views.trainbot, name='trainbot'),
    path('perfil/', views.perfil, name='perfil'),
    path('changePassword',views.change_password, name='change_password'),
    path('reportes/', views.reportes, name='reportes'),
    path('reporteAtendido/<slug:identificador>', views.resolverReporte, name='reporteAtendido'),
    path('reporte/<slug:identificador>', views.reporte, name='reporte'),
    path('conversaciones/', views.conversaciones, name='conversaciones'),
    path('conversacion/<slug:identificador>', views.conversacion, name='conversacion'),
    path('user/<slug:identificador>', views.del_user, name='deleteUser'),
    path('searchReport/', views.searchReport, name='searchReport'),
    path('searchConversacion/', views.searchConversacion, name='searchConversacion'),
    path('users/', views.users, name='users'),
]

proyecto_is/urls.py
from django.urls import path
from users_auth.urls import urlpatterns as account_urls
from dashboard.urls import urlpatterns as dashboard_urls
from django.conf.urls import include
from . import views
from django.conf.urls import url
from dashboard.views import ReportCreate

urlpatterns = [
    path('', views.index, name='index'),
    path('chatbot/', views.chatear, name='chatear'),
    path('createCita', ReportCreate.as_view(), name='createCita'),
    path('account/',include((account_urls, 'account'), namespace='account')),    
    path('dashboard/',include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^api/chatterbot/', views.ChatterBotApiView.as_view(), name='chatterbot'),
    url(r'^api/chatterbotAdmin/', views.ChatterBotApiViewAdmin.as_view(), name='chatterbotadmin'),
]

users_auth/urls.py
from django.contrib.auth import views as django_views
from django.urls import path
from django.urls import reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),  
    path('password-reset/',
         django_views.PasswordResetView.as_view(
             subject_template_name = 'account/password_reset_subject.txt',
             success_url = reverse_lazy('account:password_reset_done'),
             template_name='account/password_reset.html',
             email_template_name='account/password_reset_email.html',
         ),
         name='password_reset'),
    path('password-reset/done/',
         django_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', 
        django_views.PasswordResetConfirmView.as_view(
            success_url = reverse_lazy('account:password_reset_complete'),
            template_name='account/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'),
    path('password-reset/complete', 
        django_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html'
            ), 
            name='password_reset_complete'
        ),
]

dashboard/models.py
from django.db import models
from django.utils.timezone import now 

class Conversacion(models.Model):
    create = models.DateTimeField(default=now , editable=False)
    solucionado = models.BooleanField(default=False)
    texto = models.CharField(max_length=512)
    enviadopor = models.CharField(max_length=36)
    response = models.CharField(max_length=36, default='BOT')


class Reporte(models.Model):
    create = models.DateTimeField(default=now, editable=False)
    problema = models.CharField(max_length=1000)
    atendido = models.BooleanField(default=False)
    modelopc = models.CharField(max_length=100)
    cliente = models.CharField(max_length=150)
    fecha = models.DateField(default=now)
    hora = models.TimeField(default=now)
    def __str__(self):
        return self.modelopc

proyecto_is/forms.py
from django import forms

dashboard/views.py
from django.shortcuts import render, redirect
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.admin.views.decorators import user_passes_test
from users_auth.models import User
from .models import Conversacion
from django.db.models import Subquery
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import views as django_views
from datetime import date
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic.edit import CreateView
from .models import Reporte
from django.http import JsonResponse
from django.urls import reverse_lazy
from dashboard.models import Conversacion, Reporte


def superuser_required(
    view_func=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url="account:login"
):
    actual_decorator = user_passes_test(
        lambda u: u.is_active and u.is_admin or u.is_superuser,
        login_url=login_url,
        redirect_field_name=redirect_field_name,
    )
    if view_func:
        return actual_decorator(view_func)
    return actual_decorator

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            messages.success(request, 'Tu contraseña se actualizo correctamente')
            return redirect('/dashboard/')
        else:
            messages.error(request, 'Corrige el error.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'dashboard/change_password.html', {'form': form})

@login_required
def profile(request):
    today = date.today()
    today_filter = Conversacion.objects.filter(create__year=today.year,
                                       create__month=today.month,
                                       create__day=today.day).distinct('enviadopor').count()
    reparacionesNuevas = Reporte.objects.filter(create__year=today.year,
                                       create__month=today.month,
                                       create__day=today.day).count()
    reparacionesPendientes = Reporte.objects.filter(atendido=False).count()
    context = {
        'todayConsultas' : today_filter,
        'todayReportes' :reparacionesNuevas,
        'todayPendientes' : reparacionesPendientes
    }
    return render(request, 'dashboard/profile.html', context)

@login_required
def searchReport(request):
    if request.POST.get('campo') and request.POST.get('opcion'):
        value = request.POST.get('campo')
        opcion = request.POST.get('opcion')
        if opcion=='1':    
            try:
                dateFilter = datetime.datetime.strptime(value, "%d/%m/%y").date()
                search = Reporte.objects.filter(create__icontains=dateFilter)
                context = {
                    'reportes' : search
                }
                return render(request,'dashboard/reportes.html',context)   
            except ValueError:
                messages.warning(request, "Formato incorrecto")
                return redirect('/dashboard/reportes')
        elif opcion=='2':   
            search = Reporte.objects.filter(cliente__icontains=value).order_by('-create')
            context = {
                'reportes' : search
            }
            return render(request,'dashboard/reportes.html',context)
        else:            
            messages.warning(request, "La opcion enviada no existe")
            return redirect('/dashboard/reporte')
    else:
        messages.warning(request, "Error falta llenar algun campo")
        return redirect('/dashboard/reporte')

@login_required
def searchConversacion(request):
    if request.POST.get('campo'):
        value = request.POST.get('campo')
        try:
            dateFilter = datetime.datetime.strptime(value, "%d/%m/%y").date()
            search = Conversacion.objects.filter(create__icontains=dateFilter)
            context = {
                'conversaciones' : search
            }
            return render(request,'dashboard/conversaciones.html',context)   
        except ValueError:
            messages.warning(request, "Formato incorrecto")
            return redirect('/dashboard/conversaciones')
    else:
        messages.warning(request, "Error falta llenar algun campo")
        return redirect('/dashboard/conversaciones')

@login_required
def trainbot(request):
    return render(request, 'dashboard/trainbot.html')

@login_required
def perfil(request):
    return render(request, 'dashboard/perfil.html')

@login_required
def reportes(request):
    reportes_list = Reporte.objects.filter(
        pk__in=Subquery(
            Reporte.objects.all().values('pk')
        )
    ).order_by("fecha")
    paginator = Paginator(reportes_list, 8)
    page = request.GET.get('page')
    reportes = paginator.get_page(page)
    context = {
        'reportes' : reportes
    }
    return render(request, 'dashboard/reportes.html', context)

@login_required
def conversaciones(request):
    conversaciones_list = Conversacion.objects.filter(
        pk__in=Subquery(
            Conversacion.objects.distinct('enviadopor').values('pk')
        )
    ).order_by("-id")
    paginator = Paginator(conversaciones_list, 8)
    page = request.GET.get('page')
    conversaciones = paginator.get_page(page)
    context = {
        'conversaciones' :conversaciones
    }
    return render(request, 'dashboard/conversaciones.html', context)

@login_required
def del_user(request, identificador):    
    try:
        u = User.objects.get(id = identificador)
        user = request.user
        if u.email==request.user.email:
            user.is_active = False
            user.save()
            kwargs = {
            'template_name' : 'account/logout.html',
            'next_page': '/'
            }
            return django_views.LogoutView.as_view(**kwargs)(request, **kwargs)
        else:
            print("Entre")
            u.is_active = False
            u.save()
            return redirect('/dashboard/users')
    except:
        return render(request, 'dashboard/usuarios.html')


@login_required
def resolverReporte(request, identificador):
    reporte = Reporte.objects.get(id = identificador)
    reporte.atendido = True
    reporte.save()
    return redirect('/dashboard/reportes')

@login_required
def conversacion(request, identificador):
    conversacion = Conversacion.objects.filter(enviadopor="%s" %identificador).all().order_by('id')
    context = {
        'conversacion' : conversacion
    }
    return render(request, 'dashboard/conversacion.html', context)

@login_required
def reporte(request, identificador):
    reporte = Reporte.objects.get(pk=identificador)
    print(reporte.id)
    context = {
        'reporte' : reporte
    }
    return render(request, 'dashboard/reporte.html', context)

@superuser_required
def users(request):
    clientes = User.objects.all()
    context = {
        'clientes' : clientes
    }
    return render(request, 'dashboard/usuarios.html', context)

class AjaxableResponseMixin:
    def form_invalid(self, form):
        if self.request.is_ajax():
            return render(self.request, 'snippet/createCita.html', {'form' : form}, status=505)
        
    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk' : self.object.pk,
                'problema' : self.object.problema,
                'modelopc' : self.object.modelopc,
                'cliente' : self.object.cliente,
                'hora' : self.object.hora,
                'fecha' : self.object.fecha,
            }
            return JsonResponse('Ok', safe=False)
        else:
            return response

#CLASS BASED VIEWS PARA Reportes
class ReportCreate(AjaxableResponseMixin, CreateView):
    model = Reporte
    fields = ['problema', 'modelopc', 'cliente', 'fecha','hora']
    def form_valid(self, form):
        busqueda = Reporte.objects.filter(fecha=form.instance.fecha)
        existe = busqueda.filter(hora=form.instance.hora).count()
        if existe==0:
            idC = self.request.POST['idC']
            problema = self.request.POST['problema']
            cliente = self.request.POST['cliente']
            modelo = self.request.POST['modelopc']
            hora = self.request.POST['hora']
            fecha = self.request.POST['fecha']
            conversa = Conversacion(texto="Entendido, guarde una cita para "+cliente+" con el modelo de computadora "+modelo+" para el dia "+fecha+" a las "+hora+ " con el siguiente diagnostico "+problema,enviadopor=idC,solucionado=True)
            conversa.save()
            return super(ReportCreate, self).form_valid(form)
        else:
            return render(self.request, 'snippet/createCita.html', {'form' : form}, status=500)
    def get_success_url(self):
        return reverse_lazy('createCita')

proyecto_is/views.py
from django.shortcuts import render,redirect 
import datetime
from django.contrib.auth.decorators import login_required
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from django.views.generic.base import TemplateView
from django.views.generic import View
import json
from chatterbot.conversation import Statement
from django.http import JsonResponse
from chatterbot.trainers import ChatterBotCorpusTrainer
import random
from dashboard.models import Conversacion, Reporte
import string
from chatterbot.comparisons import LevenshteinDistance
from chatterbot.parsing import datetime_parsing
from chatterbot.response_selection import get_most_frequent_response
from datetime import datetime
from chatterbot.trainers import ListTrainer
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from users_auth.forms import ReporteForm

levenshtein_distance = LevenshteinDistance()

class ChatterBotApiView(View):
    bot = ChatBot(**settings.CHATTERBOT)
    def post(self, request, *args, **kwargs):
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text'] == '' or input_data['id'] == '':
            return JsonResponse({
                'text': [
                    'El atributo texto o id son requeridos'
                ]
            }, status=400)
        else:
            conversa = Conversacion(texto=input_data['text'],enviadopor=input_data['id'], response='USER')
            conversa.save()
            respuesta = Statement(input_data['text'])
            if levenshtein_distance.compare(respuesta, Statement('Si funciono'))>0.65 or levenshtein_distance.compare(respuesta, Statement('Se soluciono el problema'))>0.65:
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                response = self.bot.get_response(input_data)
                print(response)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'], solucionado=True)
                conversa.save()
            elif levenshtein_distance.compare(respuesta, Statement('Necesito una cita de reparacion'))>0.65:
                response = Statement('Cita de reparacion')
                elementosActualizar = Conversacion.objects.filter(enviadopor="%s" %input_data['id']).all().order_by('id')
                for elemento in elementosActualizar:
                    elemento.solucionado = True
                    elemento.save()
                conversa = Conversacion(texto='Por favor llena el siguiente formulario para agendar tu cita',enviadopor=input_data['id'])
                conversa.save()
            else:
                response = self.bot.get_response(input_data)
                conversa = Conversacion(texto=str(response),enviadopor=input_data['id'])
                conversa.save()
                print(type(response))
            response_data = response.serialize()
            return JsonResponse(response_data, status=200)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

class ChatterBotApiViewAdmin(View):
    def post(self, request, *args, **kwargs):
        bot = ChatBot(**settings.CHATTERBOT)
        input_data = json.loads(request.body.decode('utf-8'))
        if input_data['text1'] == '' or input_data['text2'] == '':
            return JsonResponse({
                'text': [
                    'Los campos texto son requeridos'
                ]
            }, status=400)
        else:
            respuesta = Statement(input_data['text1'])
            correccion = Statement(input_data['text2'])
            trainer = ListTrainer(bot)
            trainer.train([
                input_data['text1'],
                input_data['text2']
            ])
            response = "Nueva respuesta aprendida a la pregunta " +input_data['text1'] + " respondere " + input_data['text2']
            response_data = json.dumps(response)
            return JsonResponse(response_data, status=200, safe=False)
    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'name': self.bot.name
        })

def index(request):
    return render(request, 'chatbot/index.html')

def chatear(request):
    letters = string.ascii_lowercase
    identificador = ''.join(random.choice(letters) for i in range(12))
    form = ReporteForm
    return render(request, 'chatbot/chatbot.html', {'idC':identificador, 'form':form})

proyecto_is/templates/dashboard/change_password.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="row cotainer">
    <div class="container">
    <h2 class="center" data-aos="fade-up">Cambiar contraseña</h2>
    <br>
    <div class="col s12 m6">
        <form method="post" class="container">
                {% csrf_token %}
            <div class="input-field">
                <label for="id_old_password" class="active">Contaseña antigua:</label>
                {{ form.old_password }}
                {% for error in form.old_password.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="input-field">
                    <label for="id_new_password1" class="active">Contaseña nueva:</label>
                    {{ form.new_password1 }}
                    {% for error in form.new_password1.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="input-field">
                        <label for="id_new_password2" class="active">Confirmacion contraseña nueva:</label>
                        {{ form.new_password2 }}
                        {% for error in form.new_password2.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %}
                    </div>
            <p>{{ form.new_password1.help_text }}</p>
            <button type="submit" class="waves-effect waves-light btn">Guardar cambios</button>
        </form>
    </div>
    <div class="col s12 m6">
        <i class="large material-icons" style="font-size: 300px;">lock</i>
    </div>
</div>
</div>


{% endblock %}

proyecto_is/templates/dashboard/conversaciones.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="row sidenav-margin">
    <div class="container">
        <div class="col s12">
            <div class="flex">
                <h2 class="center" data-aos="fade-up">Conversaciones generadas con bot</h2>
                <div class="block text-right margin_base">
                </div>
            </div>
            <div class="form-container">
                <form action="{% url 'dashboard:searchConversacion' %}" method="post">
                    {% csrf_token %}
                    <div class=" col s1">
                        <p><i class="small material-icons">search</i></p>
                    </div>
                    <div class="search col s11">
                        <input id="campo" required="required" name="campo" aria-invalid="false"
                            placeholder="Formato de la fecha: dd/mm/aa" type="text" value="">
                    </div>
                    <input type="submit" style="position: absolute; left: -9999px" />
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                    {% endif %}
                </form>
                <table class="highlight">
                    <thead>
                        <tr>
                            <th></th>
                            <th style="text-align: center;">Problema solucionado</th>
                            <th style="text-align: center;">Fecha</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for conversacion in conversaciones%}
                            <tr>
                                <th style="text-align: center;"><i class="material-icons">assignment</i></th>
                                <th style="text-align: center;">{% if conversacion.solucionado %}<i class="small material-icons">check</i>{% else %}<i class="small material-icons">close</i>{% endif %}</th>
                                <th style="text-align: center;">{{ conversacion.create }}</th>
                                <th><a class="waves-effect waves-light btn" href="{% url 'dashboard:conversacion' identificador=conversacion.enviadopor %}" >Ver</a></th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if conversaciones.has_other_pages %}
            <div class="pagination center">
                <span class="page-links">
                    {% if conversaciones.has_previous %}
                    <a href="?page={{ conversaciones.previous_page_number }}"><i
                            class="material-icons ">keyboard_arrow_left</i></a>
                    {% endif %}
                    <span class="page-current">
                        Pagina {{ conversaciones.number }} de {{ conversaciones.paginator.num_pages }}.
                    </span>
                    {% if conversaciones.has_next %}
                    <a href="?page={{ conversaciones.next_page_number }}"> <i
                            class="material-icons ">keyboard_arrow_right</i></a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

proyecto_is/templates/dashboard/perfil.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<br>
<h1 class="center" data-aos="fade-up">Perfil</h1>
<div class="row container">
    <div class="col s12 m8">
        <h2 class="header">{{ user.first_name }} {{ user.last_name }}</h2>
        <div class="card horizontal">
            <div class="card-image">
                <img class="responsive" src="{% static 'images/userProfile.png' %}">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <h5>Correo: {{ user.email }}</h5>
                    <h5>Privilegios: {% if user.is_admin %}Administrador{% else %}Tecnico{% endif %}</h5>
                    <a class="waves-effect waves-light btn" href="{% url 'dashboard:change_password' %}">Cambiar contraseña</a>
                    <a class="waves-effect waves-light btn" href="{% url 'dashboard:deleteUser' identificador=user.id %}" >Eliminar cuenta</a>
                    
                </div>
            </div>
        </div>
        {% if user.is_superuser %}
        <a class="waves-effect waves-light btn" href="{% url 'account:signup' %}" style="left: 40%;">Agregar usuario</a>
        {% endif %}
    </div>    
</div>

{% endblock %}

proyecto_is/templates/dashboard/reporte.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<br>
<h1 class="center">Reporte {{ reporte.id }}</h1>
<div class="container">
    <h4>Cliente: {{reporte.cliente}}</h4>
    <h4>Modelo computadora: {{reporte.modelopc}}</h4>
    <h4>Fecha: {{ reporte.fecha }} a las  {{ reporte.hora }}</h4>
    <h4>Diagnostico otorgado: {{ reporte.problema }}</h4>
    <a class="waves-effect waves-light btn" href="{% url 'dashboard:reporteAtendido' identificador=reporte.id %}">Marcar como solucionado</a>
</div>
{% endblock %}

proyecto_is/templates/dashboard/reportes.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="row sidenav-margin">
    <div class="container">
        <div class="col s12">
            <div class="flex">
                <h2 class="center" data-aos="fade-up">Reportes reparaciones</h2>
                <div class="block text-right margin_base">
                </div>
            </div>
            <div class="form-container">
                <form action="{% url 'dashboard:searchReport' %}" method="post">
                    {% csrf_token %}
                    <div class=" col s3">
                        <select name="opcion" onchange="place();" id="opcion">
                            <option value="1">Fecha</option>
                            <option value="2">Nombre</option>
                        </select>
                    </div>
                    <div class="search col s9">
                        <input id="campo" required="required" name="campo" aria-invalid="false"
                            placeholder="Formato de la fecha: dd/mm/aa" type="text" value="">
                    </div>
                    <input type="submit" style="position: absolute; left: -9999px" />
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                    {% endif %}
                </form>
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Cliente</th>
                            <th>Modelo computadora</th>
                            <th>Fecha</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reporte in reportes %}
                        <tr>
                            <th>{{reporte.cliente}}</th>
                            <th>{{reporte.modelopc}}</th>
                            <th>{{reporte.fecha}} a las {{reporte.hora}}</th>
                            {% if reporte.atendido %}
                            <th><i class="small material-icons">check</i></th>
                            {% else %}
                            <th><i class="small material-icons">close</i></th>
                            {% endif %}
                            <th><a class="waves-effect waves-light btn"
                                    href="{% url 'dashboard:reporte' identificador=reporte.id %}">Ver</a></th>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if reportes.has_other_pages %}
            <div class="pagination center">
                <span class="page-links">
                    {% if reportes.has_previous %}
                    <a href="?page={{ reportes.previous_page_number }}"><i
                            class="material-icons ">keyboard_arrow_left</i></a>
                    {% endif %}
                    <span class="page-current">
                        Pagina {{ reportes.number }} de {{ reportes.paginator.num_pages }}.
                    </span>
                    {% if reportes.has_next %}
                    <a href="?page={{ reportes.next_page_number }}"> <i
                            class="material-icons ">keyboard_arrow_right</i></a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    function place() {
        if (document.getElementById('opcion').value == "1") {
            document.getElementsByName('campo')[0].placeholder = "Formato de la fecha: dd/mm/aa";
        } else {
            document.getElementsByName('campo')[0].placeholder = "Introduce el nombre";
        }
    }
</script>

{% endblock %}

proyecto_is/templates/dashboard/usuarios.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<br>
<h1 class="center" data-aos="fade-up">Usuarios</h1>
<div class="row container">
    {% for cliente in clientes %}
        {% if cliente.is_active %}
            <div class="col s12 m6">
                <h2 class="header">{{ cliente.first_name }} {{ cliente.last_name }}</h2>
                <div class="card horizontal">
                    <div class="card-image">
                        <img class="responsive" src="{% static 'images/userProfile.png' %}">
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <h5>{{ cliente.email }}</h5>
                            <h5>{% if cliente.is_superuser %}Administrador{% else %}Tecnico{% endif %}</h5>
                            <a class="waves-effect waves-light btn" href="{% url 'dashboard:deleteUser' identificador=cliente.id %}">Eliminar cuenta</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}